<a href="https://colab.research.google.com/github/SujithSaiSripadam/Deep_Learning/blob/main/NN_for_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing libraries**

In [18]:
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch
import numpy as np
import torch.nn.functional as F

In [9]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

# **Creating training data and dataloaders**

In [10]:
train_ds = TensorDataset(inputs,targets)

In [11]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size ,shuffle=True)

# **Defining Model**

In [12]:
model = nn.Linear(3,2)

In [16]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4109, -0.4979, -0.4067],
         [ 0.3546,  0.2466,  0.2672]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1263, -0.3934], requires_grad=True)]

# **Generate Predictions**

In [17]:
pred = model(inputs)

In [24]:
error = F.mse_loss(pred,targets)
loss_fn = F.mse_loss

In [20]:
error

tensor(7889.9941, grad_fn=<MseLossBackward0>)

# **Optimizing**

In [25]:
opt = torch.optim.SGD(model.parameters(),lr = 1e-5)

# **Training**

In [48]:
def fit(n_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(n_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()

            if((epoch+1)%10 == 0 ):
                print("for epoch[{}/{}] ;  loss = {:}".format(epoch+1,n_epochs,loss.item()))



In [51]:
fit(100,model,loss_fn,opt,train_dl)

for epoch[10/100] ;  loss = 0.7915599942207336
for epoch[10/100] ;  loss = 1.3933436870574951
for epoch[10/100] ;  loss = 0.8927839398384094
for epoch[20/100] ;  loss = 1.074581265449524
for epoch[20/100] ;  loss = 0.8577839732170105
for epoch[20/100] ;  loss = 1.1959586143493652
for epoch[30/100] ;  loss = 1.4494562149047852
for epoch[30/100] ;  loss = 0.6746825575828552
for epoch[30/100] ;  loss = 0.9345458745956421
for epoch[40/100] ;  loss = 1.0149915218353271
for epoch[40/100] ;  loss = 0.8705955743789673
for epoch[40/100] ;  loss = 1.2474825382232666
for epoch[50/100] ;  loss = 1.4183571338653564
for epoch[50/100] ;  loss = 0.7811489105224609
for epoch[50/100] ;  loss = 0.9509376287460327
for epoch[60/100] ;  loss = 0.7685837745666504
for epoch[60/100] ;  loss = 1.2283316850662231
for epoch[60/100] ;  loss = 1.1364465951919556
for epoch[70/100] ;  loss = 1.1228605508804321
for epoch[70/100] ;  loss = 0.8455299139022827
for epoch[70/100] ;  loss = 1.1808159351348877
for epoch[80/1

In [54]:
model(torch.tensor([[72,68,42.]]))

tensor([[57.5209, 70.5208]], grad_fn=<AddmmBackward0>)

In [55]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [57]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [58]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 56.9705,  70.3356],
        [ 82.0103, 100.5813],
        [118.2000, 132.8277],
        [ 20.8145,  37.7743],
        [101.8501, 118.4828],
        [ 55.7227,  69.2603],
        [ 81.8652, 100.6788],
        [118.4920, 133.4350],
        [ 22.0622,  38.8496],
        [102.9527, 119.6557],
        [ 56.8253,  70.4332],
        [ 80.7626,  99.5060],
        [118.3451, 132.7301],
        [ 19.7119,  36.6015],
        [103.0979, 119.5581]], grad_fn=<AddmmBackward0>)