<a href="https://colab.research.google.com/github/SujithSaiSripadam/Agrochain/blob/main/Simple_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch

In [13]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [14]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')


In [15]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [16]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [17]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)

In [27]:
def model(x):
    return x @ w.t()+b

In [38]:
def mse(z,y):
    dif = z - y
    return torch.sum(dif*dif)/dif.numel()

In [45]:
for i in range(10000):
    pred = model(inputs)
    loss = mse(pred,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [46]:
print(loss)

tensor(0.5904, grad_fn=<DivBackward0>)


In [47]:
print(pred)

tensor([[ 57.4250,  70.6077],
        [ 82.0446, 100.4828],
        [118.6495, 132.9100],
        [ 21.0485,  36.9775],
        [101.9633, 119.1858]], grad_fn=<AddBackward0>)


In [48]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
